### ISSUE TITLE
Peilen uit polygonen (peil- + boezemvakken)

### ISSUE THREAD

**Issue by DanielTollenaar** [d2hydro/bressen#1]
We maken een gebied dekkende peilenkaart om zo de richting van de bres-offset te bepalen: de kant van het laagste peil ten opzichte van de kering (polylijn). Deze peilenkaart (polygonen) is invoer in de module naast de keringen (polylijnen) en de bressen (punten)

Ontwikkelen van bressen.peilvlakken sub-module met:
- [x] Mergen van vlakkenbestanden; peilvlakken los van watervlakken
- [x] Bepaling 1 `peil` uit 1 of meerdere velden uit verschillende invoerbestanden
- [x] Opslaan van resultaat in styled GeoPackage

**Comment by DanielTollenaar** [comment]
Bovenstaande acties zijn uitvoerbaar met https://github.com/d2hydro/bressen/blob/main/scripts/test_set.py. Dit levert een styled GeoPackage met lagen `watervlakken` en `peilvlakken` die er in QGIS zo uitziet:

![Image](https://github.com/d2hydro/bressen/assets/14051252/f6a5a5c7-908d-4473-b5f7-635e5f0bc807)

**Comment by RbTsen** [comment]
Ha Daniel,

Ik vroeg me even af, er wordt op dit moment geen actie van ons verwacht toch, in de github?

**Comment by DanielTollenaar** [comment]
> Ha Daniel,
> 
> Ik vroeg me even af, er wordt op dit moment geen actie van ons verwacht toch, in de github?

Ha @RbTsen, nee, tenzij je hierboven, of in issue #2 iets geks ziet. Dan kun je hier hier kwijt. Ik verwacht de 30 brespolygonen uit #2 vrijdag te leveren.
